name: Go Release Binaries

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          check-latest: true

      - name: Get version info
        id: version
        run: |
          GIT_TAG=$(git describe --tags --exact-match 2>/dev/null || echo "dev")
          GIT_COMMIT=$(git rev-parse --short HEAD)
          echo "git_tag=${GIT_TAG}" >> $GITHUB_OUTPUT
          echo "git_commit=${GIT_COMMIT}" >> $GITHUB_OUTPUT

      - name: Build binary
        run: >-
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }}
          go build -v 
          -ldflags "-s -w -X main.gitTag=${{ steps.version.outputs.git_tag }} -X main.gitCommit=${{ steps.version.outputs.git_commit }}"
          -o alldebrid-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goos == 'windows' && '.exe' || '' }} .

      - name: Create/Update Draft Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          draft: true
          generate_release_notes: true
          files: alldebrid-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goos == 'windows' && '.exe' || '' }}
